### ISSUE TITLE
Bug / Suggestion

### ISSUE THREAD

**Issue by RhinoCD** [maotar/Binance-Advanced-Trading-Options#7]
3 things:
BUG?: - https://gyazo.com/5fd332379456025320ad98a7f97a7b71
When you shift click item (item is given through command) - it doesn't stack when just regularly trading with it without shift clicking, so the 2 items won't stack together

BUG?: - https://gyazo.com/5fd332379456025320ad98a7f97a7b71
For some reason even though the uses is set to zero in config, it won't let me trade anymore

Suggestion - Allow us to be able to be used with citizens, which would allow us to also be able to use it with model engine (or some how make it so we can use it with model engine) as i would like to make my own custom npc's and not just regular villagers for trades

**Comment by maotar** [comment]
Hi RhinoCD, judging from your screenshots it seems your comments are about another project and not the one in this repo.
